/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    'IIconPark:pineapple': typeof import('~icons/icon-park/pineapple')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDetails: typeof import('./src/components/TaskDetails.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
  }
}
